name: Competative problems

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: the-experimentals/github-workflows/.github/workflows/gradle-build.yml@main
